import { Inter } from 'next/font/google'

export const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Solana Wallet',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
