import '@/app/globals.css'
import { Inter } from 'next/font/google'
import { Provider } from './_provider'
import { Toaster } from '@/components/ui/toaster'

export const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TG message',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-950`}>
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  )
}
